#spring.application.name=Enotes_API_Service
#spring.datasource.url=jdbc:mysql://localhost:3306/enotes
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=none
#
#file.upload.path=notes/
#
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=100MB
#
## Email send config
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=sheetalshakshi143@gmail.com
#spring.mail.password=clxi kdzt cnux pqmx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.profiles.active=dev